### ISSUE TITLE
Consider adding a CITATION.cff file

### ISSUE THREAD

**Issue by PabRod** [kathiwaury/immunogenViewer#2]
Since a few months ago, GitHub generates a `Cite this repository` button (see example [here](https://github.com/PabRod/kinematics)). You can enable it by creating a `CITATION.cff` file (like [this one](https://github.com/PabRod/kinematics/blob/main/CITATION.cff)).

More context:

- About the [cff format](https://citation-file-format.github.io/).
- [Helper](https://citation-file-format.github.io/cff-initializer-javascript/#/) for creating your own.

**Comment by kathiwaury** [comment]
CITATION.cff added to repository
